### ISSUE TITLE
Treasure Hunt Game does not end if the person leaves the entire page

### ISSUE THREAD

**Issue by tootyta** [titshacking/RBSE#16]
If the person say closes the tab they're running say TreasureHunt on, the game still keeps running and does not end. And if the person leaves that game, the server kicks them. This applies for Find Four, Mancala, and Treasure Hunt.

**Comment by fantasyhacking** [comment]
I've tried fixing this issue, unfortunately all what I've tried has failed by far. The server tends to explode itself for some reason so I figured I'd rather not bother about it much.

**Comment by fantasyhacking** [comment]
This should be fixed now, will work mostly on Linux though.
