### ISSUE TITLE
No Login Server Connection

### ISSUE THREAD

**Issue by rapacapa** [titshacking/RBSE#3]
Does anyone know why I'm not getting a login connection whilst using this source? I'm not sure how I'm supposed to configure my login port with this source as there's nowhere to place it in the config file. Am I supposed to make my login port the same as my game port or am I missing something?

**Comment by AmusingThrone** [comment]
Apparently it is the same port:

https://github.com/titshacking/RBSE/blob/0ebae9952cf77e4ac29b9d54e0627c2a31683318/Core/Login.rb#L17

**Comment by rapacapa** [comment]
Hmm, I made my login port the same as my game but still no luck. No errors either, just the default starting message. http://i.imgur.com/ua3uCHW.png

**Comment by AmusingThrone** [comment]
My bad, I just remembered RBSE uses a direct login, and there is no login server. You are going to need to use Ben's server selector.

**Comment by rapacapa** [comment]
Oh okay, where can I find that?

**Comment by rapacapa** [comment]
Nevermind I found it! Didn't even know he made that, awesome. Thanks for the help!
