### ISSUE TITLE
logged_in issue [Windows]

### ISSUE THREAD

**Issue by tootyta** [titshacking/RBSE#4]
So basically when the user closes their tab or leaves the game, it doesn't update in the database logged_in so the next time the user logs in they will get Maximum Logged in Attempts Error.

**Comment by fantasyhacking** [comment]
Let me know if this works...In **TCP.rb** find the line `while (data = connection.gets("\0"))`

below that add the following:

```
	if data.length == 0
		if @parent.game_sys.iglooMap.has_key?(client.ID)
		        @parent.game_sys.iglooMap.delete(client.ID)
		end
		        if client.logged_in.to_bool == true
				@parent.mysql.updateLoggedIn(0, client.username)
			end
			client.handleBuddyOffline
		        client.removePlayerFromRoom
			self.handleRemoveClient(connection)
	end
```

**Comment by tootyta** [comment]
Unfortunately, the fix did not work.

**Comment by tootyta** [comment]
May as well close this since it can't be fixed lol
