### ISSUE TITLE
Sled Racing Issue #1

### ISSUE THREAD

**Issue by tootyta** [titshacking/RBSE#6]
Basically on Windows when Sled Racing with someone, for the packets this happens http://prntscr.com/fm3m28 .

**Comment by fantasyhacking** [comment]
Let me know if this works...in **Game.rb** look for the method `def handleSendMove(gameHandlerArgs, client)`

Inside that you will find

```
		if @sledRacing.include?(waddleID) != false
			return client.sendRoom('%xt%zm%' + gameHandlerArgs.join('%') + '%')
		end
```

replace it with:

```
		if @sledRacing.include?(waddleID) != false
			gameMove = gameHandlerArgs.join('%')
			if gameMove != ''
				return client.sendRoom('%xt%zm%' + gameMove + '%')
			end
		end
```

**Comment by tootyta** [comment]
This fix made it so it wouldn't even send the packet after the player moves. I checked the game arguments and none of the arguments seem to be defined which is probably why this is happening.
